# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'youchelai_swiftui' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for youchelai_swiftui
  pod 'HandyJSON'
  pod 'Kingfisher'
  pod 'ExytePopupView'
  pod 'AlertToast'
end
